name: ubuntu-package-manifest
version: '0.1'
base: core20
summary: Helpful utility to generate a package manifest
description: |
  Helpful utility to generate a package manifest including package names
  and versions for both deb packages and snap packges.

  Dependencies:
  * `dpkg` for including deb packages
  * `snapd` for including snap packages

  Usage:
  ubuntu-package-manifest

grade: stable
confinement: strict


#snap connect ubuntu-package-manifest:system-data
plugs:
  system-data: #snap connect ubuntu-package-manifest:system-data
    interface: system-backup

apps:
  ubuntu-package-manifest:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
    command: usr/bin/generate-manifest

parts:
  ubuntu-package-manifest:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x generate-manifest
      chmod +x list-snaps.py
      snapcraftctl build
    organize:
      generate-manifest: usr/bin/generate-manifest
      list-snaps.py: usr/bin/list-snaps.py
    stage:
      - usr/bin/generate-manifest
      - usr/bin/list-snaps.py

  ubuntu-package-manifest-dependencies:
    plugin: python
    stage-packages:
      - dpkg
      - coreutils
      - python
    python-packages:
      - pip
      - setuptools
      - wheel
      - pyyaml
